version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/ruby:2.5.1-node
    working_directory: ~/api.goodcity
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/api.goodcity

  bundle_dependencies:
    docker:
      - image: circleci/ruby:2.5.1-node
    working_directory: ~/api.goodcity
    steps:
      - run: mkdir -p ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: gem install bundler
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
         key: v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle check --path=vendor/bundle || bundle install --deployment --jobs=4 --retry=3
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  test:
    docker:
      - image: circleci/ruby:2.5.1-node
      - image: circleci/postgres:9.6.9-alpine-ram
      - image: circleci/redis:4.0.9-alpine
    working_directory: ~/api.goodcity
    environment:
      RAILS_ENV: test
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle --path vendor/bundle
      - run: bundle exec rake db:create:all db:schema:load
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter 
      - run: ./cc-test-reporter before-build
      - run:
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml
          when: always
      - store_test_results:
          path: ~/rspec
      - run: ./cc-test-reporter after-build  --exit-code $?

  audit:
    docker:
      - image: circleci/ruby:2.5.1-node
    working_directory: ~/api.goodcity
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: gem install bundler-audit
      - run: bundle-audit -v --update


  deploy:
    docker:
      - image: circleci/ruby:2.5.1-node
    working_directory: ~/api.goodcity
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle --path vendor/bundle
      - run: |
          [ "$CIRCLE_BRANCH" == "circle2" ] && bundle exec cap production invoke:rake -T || bundle exec cap staging invoke:rake -T

workflows:
  version: 2
  build-test-audit-and-deploy:
    jobs:
      # - checkout_code
      # - bundle_dependencies:
      #     requires:
      #       - checkout_code
      # - test:
      #     requires:
      #       - bundle_dependencies
      # - audit:
      #     requires:
      #       - checkout_code
      - deploy:
          # requires:
          #   - test
          #   - audit
          filters:
            branches:
              only: "circle2|master|live"
