base: &BASE
  account_sid: <%= ENV['TWILIO_ACCOUNT_SID'] %>
  auth_token: <%= ENV['TWILIO_AUTH_TOKEN'] %>
  twilio_phone_number: <%= ENV['TWILIO_PHONE_NUMBER'] %>

development:
  <<: *BASE

production:
  <<: *BASE

staging:
  <<: *BASE

test:
  <<: *BASE
